---
title: FOODS!!!
timezone: UTC
collections:
  classes-of-food:
    title: Classes of Food
    output: true
    permalink: Foods/:path
  gallery:
    title: Consequences of your diets
    output: true
  healthy-choices:
    title: Healthy Choices
    output: true
  tags:
    title: Tags
    output: true
  uploads:
    title: Uploads
    output: true
  posts:
    title: Write-ups
    output: true
snipcart_api_key: 
permalink: 
