---
title: Jekyll
timezone: UTC
collections:
  classes-of-food:
    title: Classes of Food
    output: true
  gallery:
    title: Consequences of your diets
    output: true
  posts:
    title: Posts
    output: true
  tags:
    title: Tags
    output: true
  uploads:
    title: Uploads
    output: true
